image: docker:stable

#services:
#  - docker:dind

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
#  DOCKER_HOST: tcp://docker:2375
#  DOCKER_DRIVER: overlay2

stages:
- build
- release

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.vivaconnect.co

build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - staging
    - master

release-image:
  stage: release
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

