import {
    Component, OnInit, Input, OnChanges, SimpleChanges, EventEmitter, Output, ViewChild, HostListener
} from '@angular/core';

import { NgProgressComponent } from '@ngx-progressbar/core';
import { AgGridEvent, GridApi, ColumnApi } from 'ag-grid-community';
import { takeWhile, endWith, tap } from 'rxjs/operators';
import { NgbPagination } from '@ng-bootstrap/ng-bootstrap';

import {
    ISortEvent, IDetailsTableData, IDetailsTableRequest, IDetailsTableResponse
} from 'src/app/core/interfaces/details-table.interface';

import { isInitialTableReady__Table, gettingDetailsLoader, showOverlay } from './details-table.animations';

@Component({
    selector: 'app-details-table',
    templateUrl: './details-table.component.html',
    styleUrls: ['./details-table.component.scss'],
    animations: [
        isInitialTableReady__Table,
        gettingDetailsLoader,
        showOverlay
    ]
})
export class DetailsTableComponent implements OnInit, OnChanges {

    @Input()
    details: IDetailsTableResponse[];

    @Input()
    detailsTableRequest: IDetailsTableRequest;

    @Output()
    detailsTableRequestEvent = new EventEmitter<IDetailsTableRequest>();

    @Output()
    downloadDetailsEvent = new EventEmitter<IDetailsTableRequest>();

    // getting a reference to the progress bar in the html file
    @ViewChild('gettingDetailsBar')
    private _progressBar: NgProgressComponent;

    @ViewChild('detailsTablePagination')
    private _detailsTablePagination: NgbPagination;

    private _currentDetails = null;
    pageSetTrigger = true;

    recordsInfo = {
        from: 0,
        to: 0,
        total: 0
    };

    isInitialTableReady = 'no';
    isInitialTableReady__Table = 'no';

    detailsData: IDetailsTableData[];
    gridApi: GridApi;
    gridColumnApi: ColumnApi;

    pageSizes = [3, 5, 10, 25, 50, 100];
    paginationCollectionSize;

    @HostListener('detailsTableSortChangeEvent', ['$event.detail'])
    private _onDetailsTableSortChange(detail) {
        this.onSortChange(detail);
    }

    private _emitDataTableRequestEvent(): void {
        /*
            subsequent event requests generated by:
            1 - pagination button click **onPageChange**
            2 - display length change through **onLengthChange**
            3 - searching through table **onSearchChange**
            4 - sorting table **onSortChange**
        */

        this.detailsTableRequestEvent.emit(this.detailsTableRequest);
        this.gridApi.showLoadingOverlay();
    }

    onIsInitialTableReady__Table(event) {

        // console.group(`${event.phaseName} animating`);
        // console.log(event);
        // console.log('From:', event.fromState);
        // console.log('To:', event.toState);
        // console.log('Total Time:', event.totalTime);
        // console.groupEnd();
    }

    constructor() { }

    ngOnInit() { }

    ngOnChanges(changes: SimpleChanges): void {

        if (!changes.details.isFirstChange()) {

            this._currentDetails = changes.details.currentValue;

            const details = changes.details.currentValue;

            this.detailsData = details.data;
            this.recordsInfo = details.info;

            let pages = 1;

            pages = details.info.total % this.detailsTableRequest.length >= 5
                ? Math.ceil(details.info.total / this.detailsTableRequest.length)
                : Math.floor(details.info.total / this.detailsTableRequest.length)
                ;

            this.paginationCollectionSize = (pages || 1) * 10;

            if (this.gridColumnApi) {
                this.gridColumnApi.autoSizeAllColumns();
            }

            // completing progress bar
            if (this._progressBar) {

                this._progressBar.state$
                    .pipe(
                        // tap(console.log),
                        takeWhile(value => !value.active),
                        endWith({ active: true, transform: '' })
                    )
                    .subscribe(() => this._progressBar.complete())
                    ;
            }
        }
    }

    isGettingDetailsLoaderDone(e): void {

        if (e.fromState === 'void' && e.toState === 'no') {
            // calling starting progress bar
            this._progressBar.start();
        }

        if (e.fromState === 'no' && e.toState === 'void') {
            this.isInitialTableReady__Table = 'yes';
        }
    }

    gettingDetailsBarCompleted(): void {
        this.isInitialTableReady = 'yes';
    }

    onGridReady(e: AgGridEvent): void {
        this.gridApi = e.api;
        this.gridColumnApi = e.columnApi;
    }

    onLengthChange(length: string): void {

        this.detailsTableRequest = {
            // resetting properties
            start: 0,
            sort: {
                sortKey: 'id',
                sortDir: 0
            },

            // changing properties
            length: Number(length),
            search: this.detailsTableRequest.search
        };

        // setting pagination so as to show first page
        this._detailsTablePagination.selectPage(1);

        // triggering change detection for pagination component
        this.pageSetTrigger = !this.pageSetTrigger;

        this._emitDataTableRequestEvent();
    }

    onSearchChange(text: string): void {
        this.detailsTableRequest.search = text.toLowerCase();
        this._emitDataTableRequestEvent();
    }

    onPageChange(page: number): void {
        this.detailsTableRequest.start = page - 1;
        this._emitDataTableRequestEvent();
    }

    onSortChange(sort: ISortEvent): void {
        this.detailsTableRequest.sort = sort;
        this._emitDataTableRequestEvent();
    }
}
